pr: none
trigger:
  branches:
    include:
    - main

stages:
- stage:
  jobs:
  - job:
    name: Install Terraform
    steps:
    - template: templates/terraform-install.yaml

  - job:
    name: set env variables
    steps:
    - template: templates/terraform-authentication.yaml

  - job:
    name: Run terraform to deploy
    steps:
    - template: templates/terraform-Run.yaml